version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules/
      - vendor:/var/www/html/vendor/
    restart: always
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: motorimpex-php:7.3
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules/
      - vendor:/var/www/html/vendor/
    environment:
      XDEBUG_CONFIG: "remote_host=${DOCKER_XDEBUG_HOST:-host.docker.internal} remote_enable=1"
    restart: always
    depends_on:
      - db
  db:
    image: mariadb:10.3.25
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: motorimpex
      MYSQL_USER: motorimpex
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  node_modules:
  vendor:
